project_id = "benxrhpjitojsfuyjcio"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 17

[functions.signup-tenant]
verify_jwt = false

[functions.create-appointment]
verify_jwt = false